name: aimm
description: "Ai Volume Bot."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.2.1
  get: 4.6.6
  cupertino_icons: ^1.0.8
  video_player: 2.9.1
  video_player_web: 2.2.0
  visibility_detector: ^0.4.0+2
  chewie: ^1.8.5
  url_strategy:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/